### ISSUE TITLE
Speed only shows as KB/s

### ISSUE THREAD

**Issue by eliyen** [minhdanh/tmux-network-speed#3]
I noticed on a specific server the speeds only show as KB/s, for example 14313.4 KB/s, while on other servers, this would show as 14.3 MB/s. Is there some setting that's causing this discrepancy? 

I have the format string set as follows: `set-option -g @network_speed_format "%3.1f"`

**Comment by minhdanh** [comment]
That's weird. Can you share more information about the server showing as KB/s only? Such as OS and OS version.
Also can you try running this script on that server and paste the output here:
```
#!/bin/bash
result=$(printf "%05.2f > 99.99\n" 14313.4 | bc -l)
echo $result
if [[ $result == 1 ]]; then
    vel_mb_f=$(printf "%3.1f" "14.3")
    printf "%s MB/s" $vel_mb_f
else
    vel_kb_f=$(printf "%3.1f" "14313.4")
    printf "%s KB/s" $vel_kb_f
fi
```
(Above snippet is part of the code to print the right unit, as seen here: https://github.com/minhdanh/tmux-network-speed/blob/9db90cc1ed4647afa32e204dd150581ebcd9abf2/network_speed.sh#L30-L37)

> I have the format string set as follows: set-option -g @network_speed_format "%3.1f"

That format string should not affect what unit being shown. It's just for the number.

**Comment by eliyen** [comment]
Found the culprit, running the script above results in `bc: command not found`

The OS is Ubuntu 22.04.1 LTS. Not sure why this installation doesn't include bc, but installing bc results in the correct output showing.

Thanks again for your help!
